// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Model.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Model.Models
{
    public partial class eccomerceDBContext : DbContext
    {
        public eccomerceDBContext()
        {
        }

        public eccomerceDBContext(DbContextOptions<eccomerceDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Envios> Envios { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Variante> Variante { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.EnviosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VarianteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VentasConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
