// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Ventas
    {
        public Ventas()
        {
            Envios = new HashSet<Envios>();
        }

        public int IdVenta { get; set; }
        public DateTime FechaVenta { get; set; }
        public int IdUser { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<Envios> Envios { get; set; }
    }
}