// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class UsersConfiguration : IEntityTypeConfiguration<Users>
    {
        public void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.HasKey(e => e.IdUser)
                .HasName("PK__Users__D2D14637E379E381");

            entity.HasIndex(e => e.Mail, "UQ__Users__7A212904A5B6F48E")
                .IsUnique();

            entity.Property(e => e.IdUser).HasColumnName("id_user");

            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("apellido");

            entity.Property(e => e.Clave)
                .IsRequired()
                .HasMaxLength(4000)
                .HasColumnName("clave");

            entity.Property(e => e.IdRol).HasColumnName("id_rol");

            entity.Property(e => e.Mail)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("mail");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdRolNavigation)
                .WithMany(p => p.Users)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__id_rol__336AA144");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Users> entity);
    }
}
