// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class VarianteConfiguration : IEntityTypeConfiguration<Variante>
    {
        public void Configure(EntityTypeBuilder<Variante> entity)
        {
            entity.HasKey(e => e.IdVariante)
                .HasName("PK__Variante__85058CA9111DB50F");

            entity.Property(e => e.IdVariante)
                .ValueGeneratedNever()
                .HasColumnName("id_variante");

            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("color");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("descripcion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Variante> entity);
    }
}
